vars:
  B: 2              # Number of predictions per cell
  S: 7              # Number of cells
  nc: 10
input_shape: [ 448, 448, 3 ]
activation: LReLU
backbone: [
  # from, quantity, type, params
  [ -1, 1, Conv, [ 64, 7, 2, 3 ] ],
  [ -1, 1, MaxPool, [ 2, 2 ] ],

  [ -1, 1, Conv, [ 192, 3, 1, 1 ] ],
  [ -1, 1, MaxPool, [ 2, 2 ] ],

  [ -1, 1, Conv, [ 128, 1 ] ],
  [ -1, 1, Conv, [ 256, 3, 1, 1 ] ],
  [ -1, 1, Conv, [ 256, 1 ] ],
  [ -1, 1, Conv, [ 512, 3, 1, 1 ] ],
  [ -1, 1, MaxPool, [ 2, 2 ] ],

  [ -1, 4, Block,
    [
      [ -1, 1, Conv, [ 256, 1 ] ],
      [ -1, 1, Conv, [ 512, 3, 1, 1 ] ],
    ] ],

  [ -1, 1, Conv, [ 512, 1 ] ],
  [ -1, 1, Conv, [ 1024, 3, 1, 1 ] ],
  [ -1, 1, MaxPool, [ 2, 2 ] ],

  [ -1, 2, Block,
    [
      [ -1, 1, Conv, [ 512, 1 ] ],
      [ -1, 1, Conv, [ 1024, 3, 1, 1 ] ],
    ] ],

  [ -1, 1, Conv, [ 1024, 3, 1, 1 ] ],
  [ -1, 1, Conv, [ 1024, 3, 2, 1 ] ],

  [ -1, 1, Conv, [ 1024, 3, 1, 1 ] ],
  [ -1, 1, Conv, [ 1024, 3, 1, 1 ] ],
]

head: [
  [ -1, 1, FC, [ 4096 ] ],
  [ -1, 1, Dropout, [ 0.5 ] ],
  [ -1, 1, FC, [ $S * $S * ( $nc + $B*5 ) ] ],
]
